DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS system CASCADE;

CREATE SCHEMA public;
CREATE SCHEMA system;

CREATE TABLE system.user (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP
);
