version: "3"

services:
  postgres:  
    image: postgres:13.6-bullseye
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./dump/postgres:/backup
      - ./init/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    ports:
      - 5432:5432
    env_file: .env
